import pygame

### controles / parametres

FPS = 50

H = 0
V = 1

TOUCHE_GAUCHE = pygame.K_q
TOUCHE_DROITE = pygame.K_d
TOUCHE_HAUT   = pygame.K_z
TOUCHE_BAS    = pygame.K_s
TOUCHE_SAUT   = pygame.K_SPACE
TOUCHE_COURSE = pygame.K_LSHIFT

APPUIE_GAUCHE = 0
APPUIE_DROITE = 1
APPUIE_HAUT   = 2
APPUIE_BAS    = 3
APPUIE_SAUT   = 4
APPUIE_COURSE = 5

### mario

NB_FORMES = 8

LARGEUR_MARIO       = 1 # en blocs
HAUTEUR_PETIT_MARIO = 1
HAUTEUR_GRAND_MARIO = 59/35
HAUTEUR_MARIO = [HAUTEUR_PETIT_MARIO] + [HAUTEUR_GRAND_MARIO for i in range(NB_FORMES-1)]
TAILLE_MARIO  = list(zip([LARGEUR_MARIO for i in range(NB_FORMES)], HAUTEUR_MARIO))

VERS_GAUCHE = -1
VERS_DROITE = 1
VERS_HAUT   = 1
VERS_BAS    = -1

PETIT         = 0
GRAND         = 1
FEU           = 2
TANUKI        = 3
SUPER_TANUKI  = 4
TANUKI_PIERRE = 5
MARTEAU       = 6
GRENOUILLE    = 7
BOTTE         = 8

RIEN           = 0
CARAPACE_VERTE = 1
CARAPACE_ROUGE = 2
BLOC           = 3

ETAT_BASE      = PETIT
VIES_BASE      = 5
OBJET_BASE     = RIEN
DIRECTION_BASE = VERS_DROITE

FIXE     = 0
MARCHE   = 1
SAUTE    = 2
FREINE   = 3
VOLE     = 4
NAGE     = 5

### mouvements

VITESSE_MARCHE_H     = 4   # bloc / s
VITESSE_COURSE_H     = 10  # bloc / s
ACCELERATION_H       = 10  # bloc / s²
RALENTISSEMENT_H     = 10  # bloc / s²
FREINAGE_H           = 20  # bloc / s²
TEMPS_MAX_FREINAGE_H = 1   # s

VITESSE_BASE_V       = 8.5 # bloc / s
VITESSE_COURSE_V     = 10  # bloc / s
TEMPS_PROLONGER_SAUT = 0.3 # s
VITESSE_MAX_CHUTE    = 100 # bloc / s
GRAVITATION          = -25 # bloc / s²

TEMPS_ANIMATION_MARCHE = 200 # ms

### objets / power-ups

TYPE              = 0
POSITION          = 1
VITESSE           = 2
MOMENT_APPARITION = 3
DELAI_DISPARITION = 4
ACTIF             = 5
DELAI_ACTIVATION  = 6

PIECE      = 1
CHAMPIGNON = 2
FLEUR      = 3
FEUILLE    = 4

LARGEUR_PIECE      = 1
HAUTEUR_PIECE      = 1
TAILLE_PIECE       = [LARGEUR_PIECE, HAUTEUR_PIECE]
LARGEUR_CHAMPIGNON = 1
HAUTEUR_CHAMPIGNON = 1
TAILLE_CHAMPIGNON  = [LARGEUR_CHAMPIGNON, HAUTEUR_CHAMPIGNON]
LARGEUR_FLEUR      = 1
HAUTEUR_FLEUR      = 1
TAILLE_FLEUR       = [LARGEUR_FLEUR, HAUTEUR_FLEUR]
LARGEUR_FEUILLE    = 1
HAUTEUR_FEUILLE    = 1
TAILLE_FEUILLE     = [LARGEUR_FEUILLE, HAUTEUR_FEUILLE]
TAILLE_OBJET       = [TAILLE_PIECE, TAILLE_CHAMPIGNON, TAILLE_FLEUR, TAILLE_FEUILLE]

TEMPS_SORTIE_BLOC         = 0.5 # s
HAUTEUR_SORTIE_PIECE      = 1   # bloc
HAUTEUR_SORTIE_CHAMPIGNON = 1   # bloc
HAUTEUR_SORTIE_FLEUR      = 1   # bloc
HAUTEUR_SORTIE_FEUILLE    = 2   # bloc

# vitesse à l'activation
VITESSE_PIECE      = 0   # bloc / s
VITESSE_CHAMPIGNON = 2.5 # bloc / s
VITESSE_FLEUR      = 0   # bloc / s
VITESSE_FEUILLE    = 0   # bloc / s
VITESSE_OBJET      = [VITESSE_PIECE, VITESSE_CHAMPIGNON, VITESSE_FLEUR, VITESSE_FEUILLE]

VITESSE_SORTIE_BLOC_PIECE      = HAUTEUR_SORTIE_PIECE      / TEMPS_SORTIE_BLOC
VITESSE_SORTIE_BLOC_CHAMPIGNON = HAUTEUR_SORTIE_CHAMPIGNON / TEMPS_SORTIE_BLOC
VITESSE_SORTIE_BLOC_FLEUR      = HAUTEUR_SORTIE_FLEUR      / TEMPS_SORTIE_BLOC
VITESSE_SORTIE_BLOC_FEUILLE    = HAUTEUR_SORTIE_FEUILLE    / TEMPS_SORTIE_BLOC
VITESSE_SORTIE_BLOC = [VITESSE_SORTIE_BLOC_PIECE, VITESSE_SORTIE_BLOC_CHAMPIGNON, VITESSE_SORTIE_BLOC_FLEUR, VITESSE_SORTIE_BLOC_FEUILLE]

### ennemis

# 0-4 idem objets
ETAT_ACTUEL      = 5  # infos supplémentaires nécéssaires (# HP, propriétés actives, etc)
POINT_APPARITION = 6  # recharger ennemi si sorti écran

TYPE_APPARITION    = 0
VITESSE_APPARITION = 1
ENNEMI_EN_VIE      = 2

GOOMBA      = -1
PARAGOOMBA  = -2
PARAGOOMBA2 = -3  # celui qui drop des mini goombas
MINIGOOMBA  = -4
GOOMBLOC    = -5
MAXI_GOOMBA = -6
GOOMBOTTE   = -7

KOOPA_VERT          = -10
PARAKOOPA_VERT      = -11
MAXI_KOOPA_VERT     = -12
MAXI_PARAKOOPA_VERT = -13

KOOPA_ROUGE          = -20
PARAKOOPA_ROUGE      = -21
MAXI_KOOPA_ROUGE     = -12
MAXI_PARAKOOPA_ROUGE = -13

PLANTE_PIRANHA = -30
PYRO_PIRANHA   = -31
PTOOIE         = -32 # boule à piques
PTOOIE_FIXE    = -33 # tuyau
SCROUNCH       = -34 # noirs invincibles
NIPPER         = -35 # blancs qui sautent
MAXI_PIRANHA   = -36

LAKITU  = -40
LAKITU2 = -41 # boules qui roulent au lieu de heriss

HERISS      = -50
OEUF_HERISS = -51

BRUYINSECTE         = -60
PARABRUYINSECTE     = -61
BRUYINSECTE_PORTEUR = -62 # ceux qui lancent des blocs

FRERE_MARTEAU   = -70
FRERE_MASTOC    = -71 # gros frere marteau
FRERE_BOOMERANG = -72
FRERE_PYRO      = -73

CHEEP_CHEEP_ROUGE = -80
CHEEP_CHEEP_VERT  = -81
CHEEP_CHEEP_BLEU  = -82
BEBE_CHEEP        = -83
BIG_BERTHA        = -84 # lance bébé cheep cheep
CHEEP_CHOMP       = -85

BLOUPS        = -90
BEBE_BLOUPS   = -91
NOUNOU_BLOOPS = -92

LAVA_LOTUS = -100

PODOBOO       = -110 # boule de feu
SERPENTFLAMME = -101

BILL_BALLE   = -110
BILL_BOUM    = -111 # canons
CANON        = -112
BOULET       = -113
LANCE_FLAMME = -114

SPIKE      = -120

TORTI_TAUPE = -130

CHOMP      = -140
PYRO_CHOMP = -141 # ceux qui volent

BOO      = -150
LAFLAMME = -151
FLEXIBLE = -152 # boos plateforme

SKELEREX = -160

THWOMP = -170

SOLEIL = - 180

ROTODISQUE  = -190 # boule qui tourne
ROTODISQUE2 = -191 # 2 boules

STATUE_BOWSER = -200

BOUM_BOUM = -210
LARRY     = -211
MORTON    = -212
WENDY     = -213
IGGY      = -214
ROY       = -215
LEMMY     = -216
LUDWING   = -217
BOWSER    = -218

### blocs

LARGEUR_BLOC = 1 # en blocs
HAUTEUR_BLOC = 1
TAILLE_BLOC = (LARGEUR_BLOC, HAUTEUR_BLOC)

BLOC_AIR       = 0 # rien
BLOC_SOL       = 1
BLOC_BRIQUE    = 2
BLOC_VIDE      = 3 # bloc brun quand brique/? frappé
BLOC_MYSTERE   = 4 # bloc ? jaune
BLOC_BOIS      = 5 # bloc présent dans smb3, peut avoir objet/pousser joueur
BLOC_NOTE      = 6 # CEBLOCDEMERDECODÉAVECLECUL

### Niveaux

BLOCS       = 0
PLATEFORMES = 1 # mobile et/ou traversables
ENTITES     = 2 # objets + ennemis
DECORS      = 3
BACKUP      = 4 # pour recharger zones (recup blocs, etc)

### collisions

TOLERANCE = 1e-3

CENTRE         = 0
GAUCHE         = 1
DROITE         = 2
HAUT           = 4
HAUT_GAUCHE    = 5
HAUT_DROITE    = 6
BAS            = 8
BAS_GAUCHE     = 9
BAS_DROITE     = 10

TOLERANCE_SORTIE_ECRAN = 0.25  # fois l'écran

### affichage

LARGEUR_FENETRE = 800
HAUTEUR_FENETRE = 600
TAILLE_FENETRE = (LARGEUR_FENETRE, HAUTEUR_FENETRE)

LARGEUR_FENETRE_EN_BLOCS = 20  # blocs à l'écran
LARGEUR_BLOC_FENETRE = LARGEUR_FENETRE // LARGEUR_FENETRE_EN_BLOCS  # en pixels
HAUTEUR_BLOC_FENETRE = LARGEUR_BLOC_FENETRE
TAILLE_BLOC_FENETRE = (LARGEUR_BLOC_FENETRE, HAUTEUR_BLOC_FENETRE)
HAUTEUR_FENETRE_EN_BLOCS = HAUTEUR_FENETRE // HAUTEUR_BLOC_FENETRE

G = 0
D = 1

# Decors

PLAINE  = 0
CAVERNE = 1
CIEL    = 2
CHATEAU = 3

# Sprites

IMAGE_PATH = 'images/'
MARIO_PATH = IMAGE_PATH + 'mario/'
OBJET_PATH = IMAGE_PATH + 'objets/'
BLOC_PATH  = IMAGE_PATH + 'blocs/'