import pygame

# controles / parametres

FPS = 50

H = 0
V = 1

TOUCHE_GAUCHE = pygame.K_q
TOUCHE_DROITE = pygame.K_d
TOUCHE_HAUT   = pygame.K_z
TOUCHE_BAS    = pygame.K_s
TOUCHE_SAUT   = pygame.K_SPACE
TOUCHE_COURSE = pygame.K_LSHIFT

APPUIE_GAUCHE = 0
APPUIE_DROITE = 1
APPUIE_HAUT   = 2
APPUIE_BAS    = 3
APPUIE_SAUT   = 4
APPUIE_COURSE = 5

# mario

NB_FORMES = 8

LARGEUR_MARIO       = 1 # en blocs
HAUTEUR_PETIT_MARIO = 1
HAUTEUR_GRAND_MARIO = 59/35
HAUTEUR_MARIO = [HAUTEUR_PETIT_MARIO] + [HAUTEUR_GRAND_MARIO for i in range(NB_FORMES-1)]
TAILLE_MARIO  = list(zip([LARGEUR_MARIO for i in range(NB_FORMES)], HAUTEUR_MARIO))

VERS_GAUCHE = -1
VERS_DROITE = 1
VERS_HAUT   = 1
VERS_BAS    = -1

PETIT         = 0
GRAND         = 1
FEU           = 2
TANUKI        = 3
SUPER_TANUKI  = 4
TANUKI_PIERRE = 5
MARTEAU       = 6
GRENOUILLE    = 7

RIEN           = 0
CARAPACE_VERTE = 1
CARAPACE_ROUGE = 2
BLOC           = 3

ETAT_BASE      = PETIT
VIES_BASE      = 5
OBJET_BASE     = RIEN
DIRECTION_BASE = VERS_DROITE

FIXE     = 0
MARCHE   = 1
COURS    = 2
SAUTE    = 3
FREINE   = 4
VOLE     = 5
NAGE     = 6

# mouvements

VITESSE_MARCHE_H     = 4   # bloc / s
VITESSE_COURSE_H     = 10  # bloc / s
ACCELERATION_H       = 10  # bloc / s²
RALENTISSEMENT_H     = 10  # bloc / s²
FREINAGE_H           = 20  # bloc / s²
TEMPS_MAX_FREINAGE_H = 1   # s

VITESSE_BASE_V       = 8.5 # bloc / s
VITESSE_COURSE_V     = 10  # bloc / s
TEMPS_PROLONGER_SAUT = 0.3 # s
VITESSE_MAX_CHUTE    = 100 # bloc / s
GRAVITATION          = -25 # bloc / s²

TEMPS_ANIMATION_MARCHE = 200 # ms

# objets / power-ups

TYPE              = 0
POSITION          = 1
VITESSE           = 2
MOMENT_APPARITION = 3
CHARGE            = 4
ACTIF             = 5
DELAI_ACTIVATION  = 6
DELAI_DISPARITION = 7

PIECE      = 0
CHAMPIGNON = 1
FLEUR      = 2
FEUILLE    = 3

LARGEUR_PIECE      = 1
HAUTEUR_PIECE      = 1
TAILLE_PIECE       = [LARGEUR_PIECE, HAUTEUR_PIECE]
LARGEUR_CHAMPIGNON = 1
HAUTEUR_CHAMPIGNON = 1
TAILLE_CHAMPIGNON  = [LARGEUR_CHAMPIGNON, HAUTEUR_CHAMPIGNON]
LARGEUR_FLEUR      = 1
HAUTEUR_FLEUR      = 1
TAILLE_FLEUR       = [LARGEUR_FLEUR, HAUTEUR_FLEUR]
LARGEUR_FEUILLE    = 1
HAUTEUR_FEUILLE    = 1
TAILLE_FEUILLE     = [LARGEUR_FEUILLE, HAUTEUR_FEUILLE]
TAILLE_OBJET       = [TAILLE_PIECE, TAILLE_CHAMPIGNON, TAILLE_FLEUR, TAILLE_FEUILLE]

TEMPS_SORTIE_BLOC         = 0.5 # s
HAUTEUR_SORTIE_PIECE      = 1   # bloc
HAUTEUR_SORTIE_CHAMPIGNON = 1   # bloc
HAUTEUR_SORTIE_FLEUR      = 1   # bloc
HAUTEUR_SORTIE_FEUILLE    = 2   # bloc

# vitesse à l'activation
VITESSE_PIECE      = 0   # bloc / s
VITESSE_CHAMPIGNON = 2.5 # bloc / s
VITESSE_FLEUR      = 0   # bloc / s
VITESSE_FEUILLE    = 0   # bloc / s
VITESSE_OBJET      = [VITESSE_PIECE, VITESSE_CHAMPIGNON, VITESSE_FLEUR, VITESSE_FEUILLE]

VITESSE_SORTIE_BLOC_PIECE      = HAUTEUR_SORTIE_PIECE      / TEMPS_SORTIE_BLOC
VITESSE_SORTIE_BLOC_CHAMPIGNON = HAUTEUR_SORTIE_CHAMPIGNON / TEMPS_SORTIE_BLOC
VITESSE_SORTIE_BLOC_FLEUR      = HAUTEUR_SORTIE_FLEUR      / TEMPS_SORTIE_BLOC
VITESSE_SORTIE_BLOC_FEUILLE    = HAUTEUR_SORTIE_FEUILLE    / TEMPS_SORTIE_BLOC
VITESSE_SORTIE_BLOC = [VITESSE_SORTIE_BLOC_PIECE, VITESSE_SORTIE_BLOC_CHAMPIGNON, VITESSE_SORTIE_BLOC_FLEUR, VITESSE_SORTIE_BLOC_FEUILLE]


# blocs / collisions

LARGEUR_BLOC = 1 # en blocs
HAUTEUR_BLOC = 1
TAILLE_BLOC = (LARGEUR_BLOC, HAUTEUR_BLOC)

TOLERANCE = 1e-3

CENTRE         = 0
GAUCHE         = 1
DROITE         = 2
HAUT           = 4
HAUT_GAUCHE    = 5
HAUT_DROITE    = 6
BAS            = 8
BAS_GAUCHE     = 9
BAS_DROITE     = 10

# affichage

LARGEUR_FENETRE = 800
HAUTEUR_FENETRE = 600
TAILLE_FENETRE = (LARGEUR_FENETRE, HAUTEUR_FENETRE)

LARGEUR_FENETRE_EN_BLOCS = 20  # blocs à l'écran
LARGEUR_BLOC_FENETRE = LARGEUR_FENETRE // LARGEUR_FENETRE_EN_BLOCS  # en pixels
HAUTEUR_BLOC_FENETRE = LARGEUR_BLOC_FENETRE
TAILLE_BLOC_FENETRE = (LARGEUR_BLOC_FENETRE, HAUTEUR_BLOC_FENETRE)
HAUTEUR_FENETRE_EN_BLOCS = HAUTEUR_FENETRE // HAUTEUR_BLOC_FENETRE

G = 0
D = 1

# Sprites

IMAGE_PATH = 'images/'
MARIO_PATH = IMAGE_PATH + 'mario/'
OBJET_PATH = IMAGE_PATH + 'objets/'
BLOC_PATH  = IMAGE_PATH + 'blocs/'